theme: jekyll-theme-cayman

title: LiSA
description: A Library for Static Analysis
google_analytics: G-S6MJSTDQJL

exclude: [README.md, release.sh, check-links.sh, schemes.pptx]

ssv-homepage: https://ssv.dais.unive.it/
